<?php
declare(strict_types=1);
namespace Webkernel\Aptitudes\Base;
define('APTITUDE_DB_PREFIX', 'apt_');
use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Aptitudes\Base\RenderHooks\CommonHooks;
use Webkernel\Aptitudes\Base\Filament\Pages\WelcomeSystemDashboard;
use Webkernel\Aptitudes\Base\Providers\SystemPanelProvider;
use Webkernel\Arcanes\QueryModules;
class BaseModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('base')
        ->name('Base')
        ->version('1.0.0')
        ->description('Base module - Auto-generated by Arcanes')
        ->viewNamespace('base')
        ->dependencies([])
        ->aliases([])
        ->providers([SystemPanelProvider::class])
        ->moduleProvides([
          'Resources' => [
            // [SomeResource::class, '*'],
            // [UserResource::class, ['admin', 'workspace']],
          ],
          'Pages' => [[WelcomeSystemDashboard::class, 'system']],
          'Widgets' => [
            // [SomeWidget::class, '*'],
            // [DashboardWidget::class, ['admin', 'workspace']],
          ],
          'middleware' => [
            // [\App\Http\Middleware\EncryptCookies::class, '*'],
          ],
          'authMiddleware' => [
            // [\App\Http\Middleware\Authenticate::class, ['admin', 'workspace']],
          ],
        ])
        ->build(),
    );
  }
  public function register(): void
  {
    parent::register();
    CommonHooks::register();
    // Register your services, bindings, etc.
    // Uncomment to bulk load providers from a specific folder
    // QueryModules::loadFromModule('base', 'Providers', true);
  }
  public function boot(): void
  {
    parent::boot();
    // Boot your module specific logic
    // Uncomment to load module resources at boot time
    // QueryModules::loadFromModule('base', 'Providers', true);
  }
}
