<?php declare(strict_types=1);
namespace Webkernel\Aptitudes\I18n;

use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Aptitudes\I18n\Http\Middleware\LanguageResolutionMiddleware;
use Webkernel\Aptitudes\I18n\RenderHooks\I18nHooks;
use Filament\Facades\Filament;
use Filament\Panel;

class I18nModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('i18n')
        ->name('I18n')
        ->version('1.0.0')
        ->description('I18n module - Auto-generated by Arcanes')
        ->viewNamespace('i18n')
        ->dependencies([])
        ->aliases([])
        ->providers([])
        ->moduleProvides([
          'Resources' => [
            // [SomeResource::class, '*'],
            // [UserResource::class, ['admin', 'workspace']],
          ],
          'Pages' => [
            //  [WelcomeSystemDashboard::class, 'system'],
          ],
          'Widgets' => [
            // [SomeWidget::class, '*'],
            // [DashboardWidget::class, ['admin', 'workspace']],
          ],
          'middleware' => [[LanguageResolutionMiddleware::class, '*']],
          'authMiddleware' => [
            // [\App\Http\Middleware\Authenticate::class, ['admin', 'workspace']],
          ],
        ])
        ->build(),
    );
  }

  public function register(): void
  {
    parent::register();
  }

  public function boot(): void
  {
    parent::boot();

    // Register I18n render hooks
    I18nHooks::register();
  }
}
