<?php
declare(strict_types=1);

namespace Webkernel\Aptitudes\WebsiteBuilder;

use Livewire\Livewire;
use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Aptitudes\WebsiteBuilder\Services\ThemeCssGenerator;
use Webkernel\Aptitudes\WebsiteBuilder\Filament\Pages\WebsiteBuilder;
use Webkernel\Aptitudes\WebsiteBuilder\Filament\System\Resources\WebsiteProjects\WebsiteProjectResource;

class WebsiteBuilderModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('website-builder')
        ->name('Website Builder')
        ->version('1.0.0')
        ->description('WebsiteBuilder module - Auto-generated by Arcanes')
        ->viewNamespace('website-builder')
        ->dependencies([])
        ->aliases([])
        ->providers([])
        ->moduleProvides([
          'Resources' => [
            [WebsiteProjectResource::class, 'system'],
            // [UserResource::class, ['admin', 'workspace']],
          ],
          'Pages' => [[WebsiteBuilder::class, 'system']],
          'Widgets' => [
            // [SomeWidget::class, '*'],
            // [DashboardWidget::class, ['admin', 'workspace']],
          ],
          'middleware' => [
            // [\App\Http\Middleware\EncryptCookies::class, '*'],
          ],
          'authMiddleware' => [
            // [\App\Http\Middleware\Authenticate::class, ['admin', 'workspace']],
          ],
        ])
        ->build(),
    );
  }

  public function register(): void
  {
    parent::register();

    $this->app->singleton(WebsiteBuilderService::class, function ($app) {
      return new WebsiteBuilderService();
    });

    $this->app->singleton(ThemeCssGenerator::class, function ($app) {
      return new ThemeCssGenerator();
    }); // All Livewire components removed to prevent layout conflicts with Filament
  }

  public function boot(): void
  {
    parent::boot();
  }
}
