<?php
declare(strict_types=1);

namespace Webkernel\Aptitudes\Panels;

use Filament\View\PanelsRenderHook;
use Webkernel\Arcanes\ModuleConfig;
use Webkernel\Arcanes\WebkernelApp;
use Filament\Support\Facades\FilamentView;

class PanelsModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('panels')
        ->name('Panels')
        ->version('1.0.0')
        ->description('Panels module - Auto-generated by Arcanes')
        ->viewNamespace('panels')
        ->dependencies([])
        ->aliases([])
        ->providers([\Webkernel\Aptitudes\Panels\PanelsProvider::class])
        ->build(),
    );
  }

  public function register(): void
  {
    parent::register();
    // Register your services, bindings, etc.
  }

  public function boot(): void
  {
    parent::boot();

    // Boot your module specific logic
  }
}
