<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    public function up()
    {
        Schema::create('platform_settings', function (Blueprint $table) {
            $table->id()->comment('Primary key for the settings table');
            $table->unsignedBigInteger('tenant_id')->default(1)->index()->comment('Tenant ID for multi-tenant context');
            $table->string('key')->comment('Unique key per tenant (e.g., PLATFORM_LICENCE)');
            $table->string('category')->index()->comment('Setting category for organization (e.g., system, layout, theme)');
            $table->json('value')->comment('Structured value containing raw value, type, metadata, etc.');
            $table->unsignedBigInteger('edited_by')->nullable()->comment('User who last modified the setting');
            $table->foreign('edited_by')->references('id')->on('users')->onDelete('set null');
            $table->timestamps();
            $table->unique(['tenant_id', 'key'], 'tenant_key_unique')->comment('Ensures uniqueness of key per tenant');
        });

        $defaultSettings = [
            [
                'tenant_id' => 1,
                'key' => 'PLATFORM_LICENCE',
                'category' => 'system',
                'value' => json_encode([
                    'value' => 'TEST',
                    'type' => 'string',
                    'label_key' => 'settings_platform_licence',
                    'description_key' => 'settings_platform_licence_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'validation_rules' => ['required', 'string']
                    ],
                    'is_public' => false,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => true,
                    'display_order' => 1,
                    'card_group' => null,
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PLATFORM_ENVIRONMENT',
                'category' => 'system',
                'value' => json_encode([
                    'value' => 'development',
                    'type' => 'select',
                    'label_key' => 'settings_platform_environment',
                    'description_key' => 'settings_platform_environment_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'options' => ['development', 'staging', 'production']
                    ],
                    'is_public' => false,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => true,
                    'display_order' => 2,
                    'card_group' => null,
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'GENERAL_LAYOUT',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => 'with_side_bar_full',
                    'type' => 'select',
                    'label_key' => 'settings_general_layout',
                    'description_key' => 'settings_general_layout_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'options' => ['with_side_bar_full', 'minimalis_side_bar']
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 10,
                    'card_group' => 'layout_general',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'SIDEBAR_WIDTH',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => '16',
                    'type' => 'number',
                    'label_key' => 'settings_sidebar_width',
                    'description_key' => 'settings_sidebar_width_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'min' => 12,
                        'max' => 24,
                        'unit' => 'rem'
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 11,
                    'card_group' => 'layout_general',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'CONTENT_PADDING',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => [
                        [
                            'sub_key' => 'x',
                            'value' => '1',
                            'type' => 'number',
                            'label_key' => 'settings_content_padding_x',
                            'description_key' => 'settings_content_padding_x_desc',
                            'required' => true,
                            'is_editable' => true,
                            'constraints' => [
                                'min' => 0,
                                'max' => 10,
                                'unit' => '%',
                            ],
                            'is_public' => true,
                            'requires_cache_clear' => false,
                            'is_fixed_order' => false,
                            'display_order' => 12,
                            'card_group' => 'layout_general',
                        ],
                        [
                            'sub_key' => 'y',
                            'value' => '2',
                            'type' => 'number',
                            'label_key' => 'settings_content_padding_y',
                            'description_key' => 'settings_content_padding_y_desc',
                            'required' => true,
                            'is_editable' => true,
                            'constraints' => [
                                'min' => 0,
                                'max' => 5,
                                'unit' => 'rem',
                            ],
                            'is_public' => true,
                            'requires_cache_clear' => false,
                            'is_fixed_order' => false,
                            'display_order' => 13,
                            'card_group' => 'layout_general',
                        ],
                    ],
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PLATFORM_NAME',
                'category' => 'general',
                'value' => json_encode([
                    'value' => 'My Application',
                    'type' => 'string',
                    'label_key' => 'settings_platform_name',
                    'description_key' => 'settings_platform_name_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'validation_rules' => ['required', 'string', 'max:100']
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 20,
                    'card_group' => 'branding',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PLATFORM_DESCRIPTION',
                'category' => 'general',
                'value' => json_encode([
                    'value' => 'My application description',
                    'type' => 'text',
                    'label_key' => 'settings_platform_description',
                    'description_key' => 'settings_platform_description_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 21,
                    'card_group' => 'branding',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PLATFORM_LOGO',
                'category' => 'branding',
                'value' => json_encode([
                    'value' => '/images/logo.png',
                    'type' => 'image',
                    'label_key' => 'settings_platform_logo',
                    'description_key' => 'settings_platform_logo_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 22,
                    'card_group' => 'branding',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PLATFORM_FAVICON',
                'category' => 'branding',
                'value' => json_encode([
                    'value' => '/images/favicon.ico',
                    'type' => 'image',
                    'label_key' => 'settings_platform_favicon',
                    'description_key' => 'settings_platform_favicon_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 23,
                    'card_group' => 'branding',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'THEME_PRIMARY_COLOR',
                'category' => 'theme',
                'value' => json_encode([
                    'value' => '#3b82f6',
                    'type' => 'color',
                    'label_key' => 'settings_theme_primary_color',
                    'description_key' => 'settings_theme_primary_color_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 30,
                    'card_group' => 'theme_colors',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'THEME_SECONDARY_COLOR',
                'category' => 'theme',
                'value' => json_encode([
                    'value' => '#64748b',
                    'type' => 'color',
                    'label_key' => 'settings_theme_secondary_color',
                    'description_key' => 'settings_theme_secondary_color_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 31,
                    'card_group' => 'theme_colors',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'SIDEBAR_BORDER_WIDTH',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => '0.1',
                    'type' => 'number',
                    'label_key' => 'settings_sidebar_border_width',
                    'description_key' => 'settings_sidebar_border_width_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'min' => 0,
                        'max' => 1,
                        'unit' => 'em'
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 40,
                    'card_group' => 'sidebar_style',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'SIDEBAR_BORDER_COLOR',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => 'rgba(var(--gray-200), 1)',
                    'type' => 'color',
                    'label_key' => 'settings_sidebar_border_color',
                    'description_key' => 'settings_sidebar_border_color_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 41,
                    'card_group' => 'sidebar_style',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'SIDEBAR_DARK_BORDER_COLOR',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => 'rgba(var(--gray-800), 1)',
                    'type' => 'color',
                    'label_key' => 'settings_sidebar_dark_border_color',
                    'description_key' => 'settings_sidebar_dark_border_color_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 42,
                    'card_group' => 'sidebar_style',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'LOADER_BACKGROUND',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => 'rgba(255, 255, 255, 0.05)',
                    'type' => 'color',
                    'label_key' => 'settings_loader_background',
                    'description_key' => 'settings_loader_background_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 50,
                    'card_group' => 'loader_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'LOADER_DARK_BACKGROUND',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => 'rgba(0, 0, 0, 0.3)',
                    'type' => 'color',
                    'label_key' => 'settings_loader_dark_background',
                    'description_key' => 'settings_loader_dark_background_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 51,
                    'card_group' => 'loader_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'LOADER_BORDER_COLOR',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => 'rgba(255, 255, 255, 0.12)',
                    'type' => 'color',
                    'label_key' => 'settings_loader_border_color',
                    'description_key' => 'settings_loader_border_color_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 52,
                    'card_group' => 'loader_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'LOADER_SPINNER_SIZE',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => '3',
                    'type' => 'number',
                    'label_key' => 'settings_loader_spinner_size',
                    'description_key' => 'settings_loader_spinner_size_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'min' => 1,
                        'max' => 5,
                        'unit' => 'rem'
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 53,
                    'card_group' => 'loader_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'LOADER_SPINNER_BORDER_WIDTH',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => '4',
                    'type' => 'number',
                    'label_key' => 'settings_loader_spinner_border_width',
                    'description_key' => 'settings_loader_spinner_border_width_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'min' => 1,
                        'max' => 10,
                        'unit' => 'px'
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 54,
                    'card_group' => 'loader_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'LOADER_SPINNER_BORDER_COLOR',
                'category' => 'layout',
                'value' => json_encode([
                    'value' => 'rgba(255, 255, 255, 0.2)',
                    'type' => 'color',
                    'label_key' => 'settings_loader_spinner_border_color',
                    'description_key' => 'settings_loader_spinner_border_color_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 55,
                    'card_group' => 'loader_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PWA_ENABLED',
                'category' => 'pwa',
                'value' => json_encode([
                    'value' => 'true',
                    'type' => 'boolean',
                    'label_key' => 'settings_pwa_enabled',
                    'description_key' => 'settings_pwa_enabled_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 60,
                    'card_group' => 'pwa_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PWA_THEME_COLOR',
                'category' => 'pwa',
                'value' => json_encode([
                    'value' => '#3b82f6',
                    'type' => 'color',
                    'label_key' => 'settings_pwa_theme_color',
                    'description_key' => 'settings_pwa_theme_color_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 61,
                    'card_group' => 'pwa_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PWA_BACKGROUND_COLOR',
                'category' => 'pwa',
                'value' => json_encode([
                    'value' => '#ffffff',
                    'type' => 'color',
                    'label_key' => 'settings_pwa_background_color',
                    'description_key' => 'settings_pwa_background_color_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => true,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 62,
                    'card_group' => 'pwa_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PWA_ORIENTATION',
                'category' => 'pwa',
                'value' => json_encode([
                    'value' => 'portrait-primary',
                    'type' => 'select',
                    'label_key' => 'settings_pwa_orientation',
                    'description_key' => 'settings_pwa_orientation_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [
                        'options' => ['portrait-primary', 'landscape-primary', 'any']
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 63,
                    'card_group' => 'pwa_settings',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'REGISTRATION_ENABLED',
                'category' => 'system',
                'value' => json_encode([
                    'value' => 'true',
                    'type' => 'boolean',
                    'label_key' => 'settings_registration_enabled',
                    'description_key' => 'settings_registration_enabled_desc',
                    'required' => true,
                    'is_editable' => true,
                    'constraints' => [],
                    'is_public' => false,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => false,
                    'display_order' => 70,
                    'card_group' => 'security',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'TERMS_URL',
                'category' => 'general',
                'value' => json_encode([
                    'value' => '/terms',
                    'type' => 'url',
                    'label_key' => 'settings_terms_url',
                    'description_key' => 'settings_terms_url_desc',
                    'required' => false,
                    'is_editable' => true,
                    'constraints' => [
                        'validation_rules' => ['nullable', 'url']
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 80,
                    'card_group' => 'legal',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'PRIVACY_URL',
                'category' => 'general',
                'value' => json_encode([
                    'value' => '/privacy',
                    'type' => 'url',
                    'label_key' => 'settings_privacy_url',
                    'description_key' => 'settings_privacy_url_desc',
                    'required' => false,
                    'is_editable' => true,
                    'constraints' => [
                        'validation_rules' => ['nullable', 'url']
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 81,
                    'card_group' => 'legal',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'COPYRIGHT_TEXT',
                'category' => 'general',
                'value' => json_encode([
                    'value' => 'Copyright © 2025 My Application. All rights reserved.',
                    'type' => 'text',
                    'label_key' => 'settings_copyright_text',
                    'description_key' => 'settings_copyright_text_desc',
                    'required' => false,
                    'is_editable' => true,
                    'constraints' => [
                        'validation_rules' => ['nullable', 'string', 'max:255']
                    ],
                    'is_public' => true,
                    'requires_cache_clear' => false,
                    'is_fixed_order' => false,
                    'display_order' => 82,
                    'card_group' => 'legal',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tenant_id' => 1,
                'key' => 'API_VERSION',
                'category' => 'system',
                'value' => json_encode([
                    'value' => '1.0',
                    'type' => 'string',
                    'label_key' => 'settings_api_version',
                    'description_key' => 'settings_api_version_desc',
                    'required' => false,
                    'is_editable' => false,
                    'constraints' => [
                        'validation_rules' => ['nullable', 'string']
                    ],
                    'is_public' => false,
                    'requires_cache_clear' => true,
                    'is_fixed_order' => true,
                    'display_order' => 90,
                    'card_group' => 'api',
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($defaultSettings as $setting) {
            DB::table('platform_settings')->insert($setting);
        }
    }


public function down()
    {
        if (Schema::hasTable('platform_settings')) {
            Schema::table('platform_settings', function (Blueprint $table) {
                $table->dropForeign(['edited_by']);
            });

            Schema::dropIfExists('platform_settings');
        }
    }
};
