<?php
declare(strict_types=1);
namespace Platform\TEst;
use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Arcanes\QueryModules;
class TEstModule extends WebkernelApp
{
    public function configureModule(): void
    {
        $this->setModuleConfig(
            $this->module()
                ->id('t-est')
                ->name('TEst')
                ->version('1.0.0')
                ->description('TEst module - Auto-generated by Arcanes')
                ->viewNamespace('t-est')
                ->dependencies([])
                ->aliases([])
                ->providers([])
                ->moduleProvides([
                    // 'Widgets' => [[SomeWidget::class, '*'], [AnotherWidget::class, ['panel_id_0']],
                    // 'Pages' => [[SomePage::class, '*'], [AdminPage::class, ['panel_id_1', 'panel_id_3']]],
                    // 'Resources' => [[SomeResource::class, '*'], [UserResource::class, ['panel_id_3', 'panel_id_0']]],
                ])
                ->build()
        );
    }
    public function register(): void
    {
        parent::register();
        // Register your services, bindings, etc.
        // Uncomment to bulk load providers from a specific folder
        // QueryModules::loadFromModule('t-est', 'Providers', true);
    }
    public function boot(): void
    {
        parent::boot();
        // Boot your module specific logic
        // Uncomment to load module resources at boot time
        // QueryModules::loadFromModule('t-est', 'Providers', true);
    }
}
