<?php
declare(strict_types=1);
namespace Webkernel\Aptitudes\Security;
use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Arcanes\QueryModules;
class SecurityModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('security')
        ->name('Security')
        ->version('1.0.0')
        ->description('Security module - Auto-generated by Arcanes')
        ->viewNamespace('security')
        ->dependencies([])
        ->aliases([])
        ->providers([\Webkernel\Aptitudes\Security\CommandGuard\CommandGuardServiceProvider::class])
        ->moduleProvides([
          // 'Widgets' => [[SomeWidget::class, '*'], [AnotherWidget::class, ['panel_id_0']],
          // 'Pages' => [[SomePage::class, '*'], [AdminPage::class, ['panel_id_1', 'panel_id_3']]],
          // 'Resources' => [[SomeResource::class, '*'], [UserResource::class, ['panel_id_3', 'panel_id_0']]],
        ])
        ->build(),
    );
  }
  public function register(): void
  {
    parent::register();
    // Register your services, bindings, etc.
    // Uncomment to bulk load providers from a specific folder
    //QueryModules::loadFromModule('security', 'Providers/Register', true);
  }
  public function boot(): void
  {
    parent::boot();
    // Boot your module specific logic
    // Uncomment to load module resources at boot time
    //QueryModules::loadFromModule('security', 'Providers/Boot', true);
  }
}
