<?php
declare(strict_types=1);

namespace Webkernel\Aptitudes\DX;

use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Arcanes\ModuleConfig;

class DXModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('dx')
        ->name('DX')
        ->version('1.0.0')
        ->description('DX module - Auto-generated by Arcanes')
        ->viewNamespace('d-x')
        ->dependencies([])
        ->aliases([])
        ->providers([])
        ->build(),
    );
  }

  public function register(): void
  {
    parent::register();

    // Register your services, bindings, etc.
  }

  public function boot(): void
  {
    parent::boot();

    // Boot your module specific logic
  }
}
