<?php
declare(strict_types=1);
namespace Webkernel\Aptitudes\SafeErrorPage;
use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Arcanes\QueryModules;
class SafeErrorPageModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('safe-error-page')
        ->name('SafeErrorPage')
        ->version('1.0.0')
        ->description('SafeErrorPage module - Auto-generated by Arcanes')
        ->viewNamespace('safe-error-page')
        ->dependencies([])
        ->aliases([])
        ->providers([])
        ->moduleProvides([
          // 'Widgets' => [[SomeWidget::class, '*'], [AnotherWidget::class, ['panel_id_0']],
          // 'Pages' => [[SomePage::class, '*'], [AdminPage::class, ['panel_id_1', 'panel_id_3']]],
          // 'Resources' => [[SomeResource::class, '*'], [UserResource::class, ['panel_id_3', 'panel_id_0']]],
        ])
        ->build(),
    );
  }
  public function register(): void
  {
    parent::register();
    // This bulk loads providers from Providers folder
    QueryModules::loadFromModule('safe-error-page', 'Providers', true /** registers recursively */);
    // Register Here your services, bindings, etc.
  }
  public function boot(): void
  {
    parent::boot();
    // Boot Here your module specific logic
  }
}
