<?php
declare(strict_types=1);

namespace Webkernel\Aptitudes\Enum;

use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Arcanes\ModuleConfig;

class EnumModule extends WebkernelApp
{
    public function configureModule(): void
    {
        $this->setModuleConfig(
            $this->module()
                ->id('enum')
                ->name('Enum')
                ->version('1.0.0')
                ->description('Enum module - Auto-generated by Arcanes')
                ->viewNamespace('enum')
                ->dependencies([])
                ->aliases([])
                ->providers([])
                ->build()
        );
    }

    public function register(): void
    {
        parent::register();

        // Register your services, bindings, etc.
    }

    public function boot(): void
    {
        parent::boot();

        // Boot your module specific logic
    }
}
