<?php declare(strict_types=1);
namespace Webkernel\Aptitudes\Platform\Connector;
use Webkernel\Arcanes\QueryModules;
use Webkernel\Arcanes\WebkernelApp;
use Webkernel\Aptitudes\Platform\Connector\Filament\Pages\LicenseManagement;

class ConnectorModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('connector')
        ->name('Connector')
        ->version('1.0.0')
        ->description('Connector module - Auto-generated by Arcanes')
        ->viewNamespace('connector')
        ->dependencies([])
        ->aliases([])
        ->providers([])
        ->moduleProvides([
          // 'Widgets' => [[SomeWidget::class, '*'], [AnotherWidget::class, ['panel_id_0']],
          // 'Pages' => [[]],
          // 'Resources' => [[SomeResource::class, '*'], [UserResource::class, ['panel_id_3', 'panel_id_0']]],
        ])
        ->build(),
    );
  }
  public function register(): void
  {
    parent::register();
    // Register your services, bindings, etc.
    // Uncomment to bulk load providers from a specific folder
    QueryModules::loadFromModule('connector', 'Providers', true);
  }
  public function boot(): void
  {
    parent::boot();
    // Boot your module specific logic
    // Uncomment to load module resources at boot time
    //QueryModules::loadFromModule('connector', 'Providers', true);
  }
}
