<?php

declare(strict_types=1);

namespace Webkernel\Aptitudes\Users;

use App\Models\User;
use Filament\Facades\Filament;
use Webkernel\Arcanes\WebkernelApp;
use Illuminate\Contracts\Auth\Access\Gate;
use Webkernel\Aptitudes\Users\Policies\UserPolicy;
use Webkernel\Aptitudes\Users\RenderHooks\UserHooks;
use Webkernel\Aptitudes\Users\Filament\Resources\Users\UserResource;
use Webkernel\Aptitudes\AccessControl\Policies\DynamicResourcePolicy;

class UsersModule extends WebkernelApp
{
  public function configureModule(): void
  {
    $this->setModuleConfig(
      $this->module()
        ->id('users')
        ->name('Users')
        ->version('1.0.0')
        ->description('Users module - Auto-generated by Arcanes')
        ->viewNamespace('users')
        ->dependencies([])
        ->aliases([])
        ->providers([UserHooks::register()])
        ->moduleProvides([
          // 'Widgets' => [[SomeWidget::class, '*'], [AnotherWidget::class, ['panel_id_0']],
          // 'Pages' => [[SomePage::class, '*'], [AdminPage::class, ['panel_id_1', 'panel_id_3']]],
          'Resources' => [[UserResource::class, ['system']]],
        ])
        ->build(),
    );
  }

  public function register(): void
  {
    parent::register();
  }

  public function boot(): void
  {
    parent::boot();

    // Enregistrer la policy User directement ici
  }
}
