<?php
declare(strict_types=1);

namespace Webkernel\Aptitudes\UI;

use Webkernel\Arcanes\WebkernelApp;

class UIModule extends WebkernelApp
{
    public function configureModule(): void
    {
        $this->setModuleConfig(
            $this->module()
                ->id('ui-module')
                ->name('UI')
                ->version('1.0.0')
                ->description('UI module - Auto-generated by Arcanes')
                ->viewNamespace('ui')
                ->dependencies([])
                ->aliases([])
                ->providers([])
                ->build()
        );
    }

    public function register(): void
    {
        parent::register();

        // Register your services, bindings, etc.
    }

    public function boot(): void
    {
        parent::boot();

        \Illuminate\View\ComponentAttributeBag::macro('twMerge', function (...$args) {
            $classes = $this->get('class', '');
            $mergedClasses = twMerge($classes, ...$args);
            return $this->merge(['class' => $mergedClasses]);
        });
    }
}
